export const LOAD_TRENDING_MOVIES_SUCCESS = 'LOAD_TRENDY_MOVIES_SUCCESS ';
export const LOAD_POPULAR_MOVIES_SUCCESS = 'LOAD_POPULAR_MOVIES_SUCCESS ';
export const BEGIN_API_CALL ='BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';
export const SEARCH_INPUT = 'SEARCH_INPUT';

